GET http://localhost:8000/posts
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamluaG8iLCJpYXQiOjE2NDEzOTE0NTgsImV4cCI6MTY0MTM5MjM1OH0.-sIKCEvbYKzpUx9B1k_OlR7uBoJIGzXUXrpI19ZrMwA

###

POST http://localhost:8000/login
Content-Type: application/json

{
    "userid": "admin",
    "password" : "admin"
}


###


GET http://localhost:8000/admin/getAdmins
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2NDMyMDM3NTIsImV4cCI6MTY0MzIwNDY1Mn0.VGmakdy6O9PQ2bCBFvy_Q77WKwY_kFtqrcLCLdG8fQ4